# Generated by Django 3.1.6 on 2021-04-30 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mystery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Mistério')),
                ('category', models.CharField(choices=[('dolorosos', 'Dolorosos'), ('gloriosos', 'Gloriosos'), ('gozosos', 'Gozosos'), ('luminosos', 'Luminosos')], max_length=50, verbose_name='Categoria')),
                ('sequence', models.IntegerField(verbose_name='Ordem da sequência')),
                ('image', models.ImageField(upload_to='photos/', verbose_name='Imagem')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de atualização')),
            ],
            options={
                'verbose_name': 'mistério',
                'verbose_name_plural': 'mistérios',
            },
        ),
    ]
